#
# sms-client
# API for sms-send functions
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSNvtCelmanApi' -name 'DefaultApi' {
    Context 'Invoke-SmsSend' {
        It 'Test Invoke-SmsSend' {
            #$TestResult = Invoke-SmsSend -SmsSendRequest "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
