#
# sms-client
# API for sms-send functions
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSNvtCelmanApi' -name 'SmsSendResponse' {
    Context 'SmsSendResponse' {
        It 'Initialize-SmsSendResponse' {
            # a simple test to create an object
            #$NewObject = Initialize-SmsSendResponse -Success "TEST_VALUE" -ErrorMessage "TEST_VALUE"
            #$NewObject | Should -BeOfType SmsSendResponse
            #$NewObject.property | Should -Be 0
        }
    }
}
