#
# sms-client
# API for sms-send functions
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSNvtCelmanApi' -name 'SmsSendRequest' {
    Context 'SmsSendRequest' {
        It 'Initialize-SmsSendRequest' {
            # a simple test to create an object
            #$NewObject = Initialize-SmsSendRequest -SenderName "TEST_VALUE" -Body "TEST_VALUE" -Phone "TEST_VALUE" -Source "TEST_VALUE"
            #$NewObject | Should -BeOfType SmsSendRequest
            #$NewObject.property | Should -Be 0
        }
    }
}
